//! Checks the Burn port against ONNX Runtime outputs of the upstream model.
//! Fixtures are generated by `scripts/prepare_model.py`.

use magika::{Error, INPUT_SIZE, Magika, NUM_LABELS, PADDING_TOKEN};

const FEATURES: &[u8] = include_bytes!("fixtures/features.i32.bin");
const SCORES: &[u8] = include_bytes!("fixtures/scores.f32.bin");

fn decode<T>(bytes: &[u8], from_le_bytes: fn([u8; 4]) -> T) -> Vec<T> {
    let (chunks, rest) = bytes.as_chunks::<4>();
    assert!(rest.is_empty());
    chunks.iter().copied().map(from_le_bytes).collect()
}

#[test]
fn matches_onnxruntime() {
    let features = decode(FEATURES, i32::from_le_bytes);
    let expected = decode(SCORES, f32::from_le_bytes);
    assert_eq!(features.len() / INPUT_SIZE, expected.len() / NUM_LABELS);

    let scores = Magika::new().scores(&features).unwrap();

    assert_eq!(scores.len(), expected.len());
    let max_error = scores
        .iter()
        .zip(&expected)
        .map(|(actual, expected)| (actual - expected).abs())
        .fold(0.0, f32::max);
    assert!(max_error < 1e-5, "max abs error {max_error}");
}

#[test]
fn rejects_invalid_length() {
    let magika = Magika::new();
    assert_eq!(magika.scores(&[]), Err(Error::InvalidLength(0)));
    assert_eq!(
        magika.scores(&[PADDING_TOKEN; INPUT_SIZE + 1]),
        Err(Error::InvalidLength(INPUT_SIZE + 1))
    );
}

#[test]
fn rejects_invalid_token() {
    let mut features = vec![PADDING_TOKEN; INPUT_SIZE];
    features[7] = PADDING_TOKEN + 1;
    assert_eq!(
        Magika::new().scores(&features),
        Err(Error::InvalidToken {
            index: 7,
            token: PADDING_TOKEN + 1
        })
    );
}
